### ISSUE TITLE
Issue: Application Restart Loop Due to Missing Import Statement

### ISSUE THREAD

**Issue by ohdearquant** [ruvnet/agentic-employment#1]
# Issue: Application Restart Loop Due to Missing Import Statement

## Description
The `app.py` file was missing an import statement, which was fixed. However, after fixing the import, the application enters an infinite restart loop. This issue occurs on a new environment with Python 3.12.1.

## Steps to Reproduce
1. Set up a new environment with Python 3.12.1.
2. Fix the missing import statement in `app.py`.
3. Run the application.

## Observed Behavior
The application starts and then continuously restarts with the following log messages:
```
INFO:     Started server process [22211]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in '.venv/lib/python3.12/site-packages/tzdata/zoneinfo/...'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [22211]
INFO:     Started server process [22217]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
...
```
This loop continues indefinitely.

## Environment
- **Python Version:** 3.12.1
- **OS:** MacOS

## Additional Information
- The issue seems to be related to the `WatchFiles` detecting changes in timezone data files (`tzdata`).
- This may be causing the server to restart repeatedly without any actual changes being made to the application code.

## Suggested Fix
- Investigate the configuration for file watching and adjust it to exclude unnecessary paths.
- Ensure that the timezone data files are not triggering a reload of the application.
- Use `lionagi` as backend orchestrator 

This issue needs to be resolved to ensure stable application startup and operation.

**Comment by ruvnet** [comment]
thanks for sending me this!

**Comment by ruvnet** [comment]
i published this as a pip and reworked the startup. 

```
pip install Agentic-Employment
```

or 
```
pip install .
```
